SET TRANSACTION NAME 'insert dsu_attribures_types';
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Text','Any raw text value is saved in an parameter like this. The value is stored in the value column of the nc_params table.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Memo','Any long text is stored as Clob in the database, this is done using the column data of the nc_params table.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Number','Any number which has no decimal point, is also stored in the value column of nc_params.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Decimal','Any numeric value with decimal points, also stored in the value column of nc_params table.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Date','Any date value, stored in DATE format in the date_value column of nc_params, there will always be a mask stored saying how the value should be displayed and saved.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Masked','Any text value which can follow a pattern, the mask rules over the formatting of the value itself, is also stored in the value column of nc_params.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('URL','Any URL value, also stored in the value column of nc_params table.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('List Value','This attribute type refers to a selection from a static list of available options, its value is stored in the column list_value_id of nc_params table, the list options grouping factor is identified by the attribute_type_def_id column in nc_params.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Table','Any attribute that helps give shape to a table in the UI of the backend.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Reference','Any attribute that can store the ID of a different object than the one who owns the attribute. This is stored in the table nc_references.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Password','Any text field which should be treated as a password in terms of hiding it from plain sight and network tracing.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Attribute Reference','Not used for most of our APIs.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Java Object','Not used for most of our APIs.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Attachment','Not used for most of our APIs.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('HTML','Not used for most of our APIs.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('XML','Not used for most of our APIs.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Currency','Not used for most of our APIs.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Reference to Object type','Not used for most of our APIs.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Reference to Attribute Type Def','Not used for most of our APIs.');
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES ('Reference to Attribute Schema','Not used for most of our APIs.');
commit;


SET TRANSACTION NAME 'CREATING_BASE_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, ISABSTRACT) VALUES ('ALL', 0);

COMMIT;

SET TRANSACTION NAME 'CREATING_PERSON_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES ('PERSON', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES (2, 'ID');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES (0, 'NAME');

    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (1,2);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (2,2);

commit;

SET TRANSACTION NAME 'CREATING_DEVICE_OBJECT_TYPE';
    
    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES ('DEVICE', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES (9, 'OWNER');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (1,3);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (2,3);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (3,3);
    
COMMIT;

SET TRANSACTION NAME 'CREATING_ROUTER_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES ('ROUTER', 3, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES (0, 'MANUFACTURE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (4,4);

COMMIT;

SET TRANSACTION NAME 'CREATING_SWITCH_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES ('SWITCH', 3, 0);
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES (4,5);

COMMIT;

SET TRANSACTION NAME 'ADDING_CREATED_DATE_ATTRIBUTE';

    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(4,'CREATED');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(5, 1);

COMMIT;

SET TRANSACTION NAME 'CREATING_TICTACTOE_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('TICTACTOE', 1, 0);
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 6);

COMMIT;

SET TRANSACTION NAME 'CREATING_TURN_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('TURN', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES_TYPES(NAME, DESCRIPTION) VALUES('Boolean', 'Any attribute that only has two values.');
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(20, 'IS_FINISHED');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PLAYER1');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PLAYER2');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'WINNER');

    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 7);    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(6, 7);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(7, 7);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(8, 7);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(9, 7);
    
COMMIT;

SET TRANSACTION NAME 'CREATING_SQUARE_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('SQUARE', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(2, 'ROW');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(2, 'COLUMN');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PIECE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 8);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(10, 8);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(11, 8);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(12, 8);

COMMIT;

SET TRANSACTION NAME 'CREATING_PLAYER_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('PLAYER', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(0, 'TYPE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 9);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(2, 9);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(13, 9);

COMMIT;

SET TRANSACTION NAME 'CREATING_PLAYER_TURN_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('PLAYER_TURN', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PLAYER');
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(9, 'PIECE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 10);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(14, 10);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(15, 10);

COMMIT;

SET TRANSACTION NAME 'CREATING_PIECE_OBJECT_TYPE';

    INSERT INTO DSU_OBJECT_TYPES(NAME, PARENT_ID, ISABSTRACT) VALUES('PIECE', 1, 0);
    
    INSERT INTO DSU_ATTRIBUTES(ATTR_TYPE_ID, NAME) VALUES(0, 'PIECE');
    
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(1, 11);
    INSERT INTO DSU_ATTR_OBJECT_TYPES(ATTR_ID, OBJECT_TYPE_ID) VALUES(15, 11);

COMMIT;

SET TRANSACTION NAME 'INSTANCIATING_TICTACTOE_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(6, 'TICTACTOE');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 1, '1');

COMMIT;

SET TRANSACTION NAME 'INSTANCIATING_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'FIRST PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 2, '2');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 2, 'ANTONIO');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 2, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'INSTANCIATING_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'SECOND PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 3, '3');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 3, 'LINDA');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 3, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'INSTANCIATING_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'THIRD PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 4, '4');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 4, 'JESUS');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 4, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'INSTANCIATING_PLAYER_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(9, 'FOURTH PLAYER');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 5, '5');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(2, 5, 'DANIELA');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(13, 5, 'HUMAN');    

COMMIT;

SET TRANSACTION NAME 'INSTANCIATING_PIECE_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(11, 'PIECE X');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 6, '6');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(16, 6, 'X');

COMMIT;

SET TRANSACTION NAME 'INSTANCIATING_PIECE_OBJECT';

    INSERT INTO DSU_OBJECTS(OBJECT_TYPE_ID, NAME) VALUES(11, 'PIECE O');
    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(1, 7, '7');    
    INSERT INTO DSU_PARAMS(ATTR_ID, OBJECT_ID, VALUE) VALUES(16, 7, 'O');

COMMIT;

/*SELECT *
FROM DSU_ATTRIBUTES_TYPES;

SELECT *
FROM DSU_ATTRIBUTES;

SELECT * 
FROM DSU_OBJECT_TYPES;

SELECT * 
FROM DSU_OBJECTS;

SELECT * 
FROM DSU_ATTR_OBJECT_TYPES;

SELECT *
FROM DSU_REFERENCE;
*/




























